### PR TITLE
Buzzwords. React, react-router, jspm, and Babel

### PR DESCRIPTION
**Pull request by davidrapson**
Sets up a basic React app with react-router, plus jspm / es6 fun.

- Adds basic routes for editor and dashboard iframe
- Removes Eventbrite link for now :disappointed: , they set a `SAMEORIGIN` so we can't show in an iframe. Probably just put a link in the event edit screen to open in a new tab.

@mattandrews Thoughts?

### CODE REVIEW

**Comment by mattandrews** [comment]
On a clean checkout I get this when I try `jspm install`:
    
        err  TypeError: Install of browser-sync to ^2.6.4 has no registry property provided.
        at /Users/mandrew/Dev/membership-event-tool/node_modules/jspm/lib/package.js:280:13
        at Array.forEach (native)
        at processDeps (/Users/mandrew/Dev/membership-event-tool/node_modules/jspm/lib/package.js:263:21)
        at setDefaults (/Users/mandrew/Dev/membership-event-tool/node_modules/jspm/lib/config/package.js:125:28)
        at PackageJSON.read (/Users/mandrew/Dev/membership-event-tool/node_modules/jspm/lib/config/package.js:112:3)
        at Promise.resolve.then.then.then.prompts (/Users/mandrew/Dev/membership-event-tool/node_modules/jspm/lib/config.js:74:25)
        at tryCatchReject (/Users/mandrew/Dev/membership-event-tool/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1183:30)
        at runContinuation1 (/Users/mandrew/Dev/membership-event-tool/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1142:4)
        at Fulfilled.when (/Users/mandrew/Dev/membership-event-tool/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:930:4)
        at Pending.run (/Users/mandrew/Dev/membership-event-tool/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:821:13)

Just me?

**Comment by davidrapson** [comment]
Just tried a fresh checkout and it worked OK. jspm doesn't reference browser-sync so not sure what's going on there. Which order did you run `npm install` and `jspm install` in, just in case it makes a difference.

**Comment by davidrapson** [comment]
Looks like something weird had gone on with the `package.json` and the `npm` and `jspm` `devDependencies` had been merged/duplicated. I don't even know.

Try again now?

**Comment by mattandrews** [comment]
Want me to give this another look now?

**Comment by davidrapson** [comment]
Not sure atm, think this is a bit pre-emptive after all

**Pull request closed without merging**
